name: docker workflow
on:
    workflow_dispatch:
    push:
        branches:
        - main
        - 'feature/*'
jobs:
  docker:
    name: containerization
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: docker login
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
